// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7HS9OLSArA5E29TIZ0lqF60bVt4XsiwI',
    appId: '1:428320069482:web:96f14d21e9890bb3607713',
    messagingSenderId: '428320069482',
    projectId: 'education-app-uz-cc7f6',
    authDomain: 'education-app-uz-cc7f6.firebaseapp.com',
    storageBucket: 'education-app-uz-cc7f6.firebasestorage.app',
    measurementId: 'G-NRS2DCT872',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgE0F079gOwHD_MASq9GfUNULBr5w3MFQ',
    appId: '1:428320069482:android:970456bd77be0878607713',
    messagingSenderId: '428320069482',
    projectId: 'education-app-uz-cc7f6',
    storageBucket: 'education-app-uz-cc7f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4wAgMOpMaVXf-o_f6fBr2-tOwaJtYEg',
    appId: '1:428320069482:ios:ca79a16225e3769c607713',
    messagingSenderId: '428320069482',
    projectId: 'education-app-uz-cc7f6',
    storageBucket: 'education-app-uz-cc7f6.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );

}